### ISSUE TITLE
URL-decode the template

### ISSUE THREAD

**Issue by girtsl** [corvus-dotnet/Corvus.UriTemplates#67]
If the template is received in response to an API request it will be URL-encoded - `https://host/api/%7b?foobar%7d` which this library apparently cannot handle.
It would be much more convenient to use a URL-encoded template directly without having to decode it first.  

Current usage:
```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = new UriTemplate(HttpUtility.UrlDecode(link.Href))
    .AddParameters(new
                   {
                       foobar = "foobar"
                   })
    .Resolve();
```

Desired usage:
```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = new UriTemplate(link.Href)
    .AddParameters(new
                   {
                       foobar = "foobar"
                   })
    .Resolve();
```

**Comment by mwadams** [comment]
Thanks for the suggestion.

My first observation is that this is an orthogonal problem - RFC6570 uri templates themselves don't support this "external encoding".

My second concern is that `HttpUtility.UrlDecode()` allocates strings. We wouldn't want the standard constructor to pay the cost of decoding (and the consequent allocations).

If you are using this code a lot, have you considered something like

```csharp
/// <summary>
/// Helpers for dealing with a URL-encoded RFC6570 uri template.
/// </summary>
public static class UrlEncodedUriTemplate
{
    /// <summary>
    /// Decodes a URL-encoded RFC6570 uri template, and creates a <see cref="UriTemplate"/> from the resulting string.
    /// </summary>
    /// <remarks>
    /// Note that this trades allocations for convenience.
    /// </remarks>
    public static UriTemplate Create(string urlEncodedUriTemplate)
    {
        return new UriTemplate(HttpUtility.UrlDecode(urlEncodedUriTemplate));
    }
}
``` 

You could then write code like:

```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = UrlEncodedUriTemplate.Create(link.Href)
    .AddParameters(new
                   {
                       foobar = "foobar"
                   })
    .Resolve();
```

**Comment by girtsl** [comment]
Thanks for considering this and the insights. You are right, decoding the template probably shouldn't be built into this library for the reasons you outline above even if it would make the consumption much more convenient.

**Comment by mwadams** [comment]
I've got another comment in #68 which might elaborate on this a little bit now I've read both of them!
