### ISSUE TITLE
Make parameters case-insensitive

### ISSUE THREAD

**Issue by girtsl** [corvus-dotnet/Corvus.UriTemplates#68]
The parameters appear to be case-sensitive while URIs are not. That is, a template `https://host/api/{?foobar}` cannot be resolved  with a parameter `new { fooBar = "fooBar }`.
If the template is returned from an API, it's impossible to know in what case it will be - it'd be necessary to always "normalize" it, which adds unncessary friction.

Current usage:
```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = new UriTemplate(link.Href.ToLower())
    .AddParameters(new
                   {
                       foobar = "fooBar"
                   })
    .Resolve();
```

Desired usage:
```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = new UriTemplate(link.Href)
    .AddParameters(new
                   {
                       fooBar = "fooBar"
                   })
    .Resolve();
```

**Comment by mwadams** [comment]
Bit of background first:

RFC6570 defines `varname` as a case-sensitive string containing at least one character [a-z], [A-Z], [0-9] or '_', or a pct-encoded UTF-8 triplet.

Specifically:

> Variable names are case-sensitive because the name might be expanded
   within a case-sensitive URI component.

https://datatracker.ietf.org/doc/html/rfc6570#section-2.3

If your API is returning parameter names using random casing, that is definitely a defect in the API - it should not be doing so.

However, I recognize that in the real world we have to deal with defective APIs!

I was going to suggest a similar approach to that described in #67 - but I now realise that these are probably two aspects of "normalizing the garbage you get back from some API or other".

However, I would caution you that this means the URI you generate will be all lowercase - which would be a problem if the URL is subsequently interpreted in a case sensitive fashion. Likewise, the URL-decoding could play havoc with any intentionally pct-encoded content in the template.

```csharp
/// <summary>
/// Helpers for dealing with an RFC6570 uri template.
/// </summary>
public static class NormalizingUriTemplate
{
    /// <summary>
    /// Decodes a URL-encoded RFC6570 uri template, and creates a <see cref="UriTemplate"/> from the resulting string.
    /// </summary>
    /// <remarks>
    /// CAUTION: This URL decodes and modifies the generated URI template to be all lowercase; this is potentially incompatible 
    //// with templates that intentionally include pct-encoded triplets, and will generate all-lowercase URLs when resolved.
    /// </remarks>
    public static UriTemplate Create(string urlEncodedUriTemplate)
    {
        return new UriTemplate(HttpUtility.UrlDecode(urlEncodedUriTemplate).ToLowerInvariant());
    }
}
```

Usage would be:
```csharp
var link = entryPoint.Links.Single(l => l.Rel == "foo-bar");
var href = NormalizingUriTemplate.Create(link.Href)
    .AddParameters(new
                   {
                       foobar = "foobar"
                   })
    .Resolve();
```

**Comment by girtsl** [comment]
Thanks for the comments, I must have missed that variable names are case-sensitive - then it's again not the concern of this library to normalize the input.
I don't think the variable name casing would be random in any given API - then it would be indeed a defective one, but it would be a particularly evil API to return a template with multiple variables having the same name only differing in case. 
I.e. in the real world the case of the variable name shouldn't matter.

**Comment by mwadams** [comment]
> Thanks for the comments, I must have missed that variable names are case-sensitive - then it's again not the concern of this library to normalize the input. I don't think the variable name casing would be random in any given API - then it would be indeed a defective one, but it would be a particularly evil API to return a template with multiple variables having the same name only differing in case. I.e. in the real world the case of the variable name shouldn't matter.

We've all seen those evil APIs :)

**Comment by mwadams** [comment]
@girtsl - Thanks so much for raising these issues. I think they might be quite helpful for people trying to understand how to use uri templates in the real world.
